CREATE TABLE IF NOT EXISTS `#__properties_category` (
  `id` int(2) NOT NULL auto_increment,
  `name` varchar(100) default NULL,
  `alias` varchar(100) default NULL,
  `parent` int(2) default NULL,
  `published` tinyint(1) NOT NULL,
  `ordering` int(1) NOT NULL,
  `checked_out` int(6) NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `access` tinyint(3) NOT NULL,
  `params` text NOT NULL,
  `metadesc` varchar(1024) NOT NULL,
  `metakey` varchar(1024) NOT NULL,
  `layout` varchar(100) NOT NULL,
  `cat_currency` int(2) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__properties_contacts` (
  `id` int(11) NOT NULL auto_increment,
  `product_id` int(11) NOT NULL,
  `aid` int(5) NOT NULL,
  `user_id` int(5) NOT NULL,
  `date` datetime NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(100) NOT NULL,
  `address` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `state` varchar(255) NOT NULL,
  `cp` varchar(100) NOT NULL,
  `text` text NOT NULL,
  `userfile` varchar(255) NOT NULL,
  `layout` varchar(255) NOT NULL,
  `published` tinyint(1) NOT NULL,
  `ip` varchar(20) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__properties_country` (
  `id` int(3) NOT NULL auto_increment,
  `name` varchar(100) NOT NULL,
  `alias` varchar(100) NOT NULL,
  `mid` int(5) NOT NULL,  
  `published` tinyint(1) NOT NULL,
  `ordering` int(11) NOT NULL default '0',
  `checked_out` int(6) NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__properties_images` (
  `id` int(5) NOT NULL auto_increment,
  `name` varchar(255) NOT NULL,
  `parent` int(4) NOT NULL,
  `published` tinyint(1) NOT NULL,
  `ordering` int(4) NOT NULL,
  `type` varchar(100) NOT NULL,
  `date` datetime NOT NULL,
  `uid` int(5) NOT NULL,
  `product_id` int(5) NOT NULL,
  `sector` varchar(255) NOT NULL,
  `text` text NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__properties_locality` (
  `id` int(6) NOT NULL auto_increment,
  `parent` int(3) NOT NULL,
  `mid` int(6) NOT NULL,
  `zipcode` int(6) NOT NULL,
  `name` varchar(100) NOT NULL,
  `alias` varchar(100) NOT NULL,
  `published` tinyint(1) NOT NULL,
  `ordering` int(11) NOT NULL default '0',
  `checked_out` int(6) NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__properties_products` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(255) NOT NULL,
  `alias` varchar(255) NOT NULL,
  `parent` int(6) NOT NULL,
  `agent_id` int(6) NOT NULL,
  `ref` varchar(50) NOT NULL,
  `type` int(6) NOT NULL,
  `cid` int(6) NOT NULL,
  `lid` int(6) NOT NULL,
  `sid` int(6) NOT NULL,
  `cyid` int(6) NOT NULL,
  `address` varchar(255) default NULL,
  `description` text NOT NULL,
  `text` text NOT NULL,
  `price` decimal(10,2) default NULL,
  `currency` int(2) NOT NULL,
  `published` tinyint(1) NOT NULL,
  `use_booking` tinyint(1) NOT NULL,
  `ordering` int(11) NOT NULL default '0',
  `video` text NOT NULL,
  `lat` float(10,6) default NULL,
  `lng` float(10,6) default NULL,
  `available` tinyint(1) NOT NULL,
  `featured` tinyint(4) NOT NULL,
  `years` int(4) NOT NULL,
  `capacity` int(2) NOT NULL,
  `rooms` int(2) NOT NULL,
  `bedrooms` tinyint(1) NOT NULL,
  `bathrooms` tinyint(1) NOT NULL,
  `garage` tinyint(1) NOT NULL,
  `area` int(5) NOT NULL,
  `covered_area` int(5) NOT NULL,
  `hits` int(6) NOT NULL,
  `listdate` date NOT NULL default '0000-00-00',
  `refresh_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `checked_out` int(6) NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `language` tinyint(1) NOT NULL,
  `access` tinyint(3) NOT NULL,
  `params` text NOT NULL,
  `metatitle` varchar(255) NOT NULL,
  `metadesc` varchar(1024) NOT NULL,
  `metakey` varchar(1024) NOT NULL,
  `layout` varchar(100) NOT NULL,
  `extra1` tinyint(1) NOT NULL default '0',
  `extra2` tinyint(1) NOT NULL default '0',
  `extra3` tinyint(1) NOT NULL default '0',
  `extra4` tinyint(1) NOT NULL default '0',
  `extra5` tinyint(1) NOT NULL default '0',
  `extra6` tinyint(1) NOT NULL default '0',
  `extra7` tinyint(1) NOT NULL default '0',
  `extra8` tinyint(1) NOT NULL default '0',
  `extra9` tinyint(1) NOT NULL default '0',
  `extra10` tinyint(1) NOT NULL default '0',
  `extra11` tinyint(1) NOT NULL default '0',
  `extra12` tinyint(1) NOT NULL default '0',
  `extra13` tinyint(1) NOT NULL default '0',
  `extra14` tinyint(1) NOT NULL default '0',
  `extra15` tinyint(1) NOT NULL default '0',
  `extra16` tinyint(1) NOT NULL default '0',
  `extra17` tinyint(1) NOT NULL default '0',
  `extra18` tinyint(1) NOT NULL default '0',
  `extra19` tinyint(1) NOT NULL default '0',
  `extra20` tinyint(1) NOT NULL default '0',
  `extra21` tinyint(1) NOT NULL default '0',
  `extra22` tinyint(1) NOT NULL default '0',
  `extra23` tinyint(1) NOT NULL default '0',
  `extra24` tinyint(1) NOT NULL default '0',
  `extra25` tinyint(1) NOT NULL default '0',
  `extra26` tinyint(1) NOT NULL default '0',
  `extra27` tinyint(1) NOT NULL default '0',
  `extra28` tinyint(1) NOT NULL default '0',
  `extra29` tinyint(1) NOT NULL default '0',
  `extra30` tinyint(1) NOT NULL default '0',
  `extra31` tinyint(1) NOT NULL default '0',
  `extra32` tinyint(1) NOT NULL default '0',
  `extra33` tinyint(1) NOT NULL default '0',
  `extra34` tinyint(1) NOT NULL default '0',
  `extra35` tinyint(1) NOT NULL default '0',
  `extra36` tinyint(1) NOT NULL default '0',
  `extra37` tinyint(1) NOT NULL default '0',
  `extra38` tinyint(1) NOT NULL default '0',
  `extra39` tinyint(1) NOT NULL default '0',
  `extra40` tinyint(1) NOT NULL default '0',
  `extratext1` varchar(255) NOT NULL,
  `extratext2` varchar(255) NOT NULL,
  `extratext3` varchar(255) NOT NULL,
  `extratext4` varchar(255) NOT NULL,
  `extratext5` varchar(255) NOT NULL,
  `extratext6` varchar(255) NOT NULL,
  `extratext7` varchar(255) NOT NULL,
  `extratext8` varchar(255) NOT NULL,
  `extratext9` varchar(255) NOT NULL,
  `extratext10` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__properties_profiles` (
  `id` int(6) NOT NULL auto_increment,
  `mid` int(6) NOT NULL default '0',
  `name` varchar(50) NOT NULL default '',
  `alias` varchar(255) NOT NULL,
  `company` varchar(255) NOT NULL default '',
  `type` int(1) NOT NULL default '0',
  `info` varchar(255) NOT NULL default '',
  `address1` varchar(50) NOT NULL default '',
  `address2` varchar(50) NOT NULL default '',
  `locality` varchar(50) NOT NULL default '',
  `pcode` varchar(10) NOT NULL default '',
  `state` varchar(50) NOT NULL default '',
  `country` varchar(50) NOT NULL default '',
  `show` tinyint(1) NOT NULL default '0',
  `email` varchar(50) NOT NULL default '',
  `phone` varchar(20) NOT NULL default '',
  `mobile` varchar(20) NOT NULL default '',
  `skype` varchar(255) NOT NULL default '',
  `facebook` varchar(255) NOT NULL default '',
  `twitter` varchar(255) NOT NULL default '',
  `googleplus` varchar(255) NOT NULL default '',
  `web` varchar(255) NOT NULL default '',
  `blog` varchar(255) NOT NULL default '',
  `image` varchar(70) NOT NULL default '',
  `logo_image` varchar(70) NOT NULL default '',
  `logo_image_large` varchar(70) NOT NULL default '',
  `published` tinyint(1) NOT NULL default '0',
  `ordering` int(3) NOT NULL default '0',
  `checked_out` int(6) NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `language` char(7) NOT NULL,
  `canaddproperties` int(3) NOT NULL,
  `canaddimages` int(2) NOT NULL,
  `canaddfeatured` int(2) NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `mid` (`mid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__properties_state` (
  `id` int(3) NOT NULL auto_increment,
  `name` varchar(100) NOT NULL,
  `alias` varchar(100) NOT NULL,
  `parent` int(5) NOT NULL,
  `mid` int(5) NOT NULL,
  `published` tinyint(1) NOT NULL,
  `ordering` int(11) NOT NULL default '0',
  `checked_out` int(6) NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__properties_type` (
  `id` int(2) NOT NULL auto_increment,
  `name` varchar(100) default NULL,
  `alias` varchar(100) default NULL,
  `parent` int(2) default NULL,
  `published` tinyint(1) NOT NULL,
  `ordering` int(1) NOT NULL,
  `checked_out` int(6) NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;